[site]
title = "Naiyu Yin"
description = "Postdoctoral Research Associate at Lehigh University."
favicon = "/favicon.svg"
last_updated = "April 2026"

[author]
name = "Naiyu Yin"
title = "Postdoctoral Research Associate"
institution = "Lehigh University"
avatar = "/bio.jpg"

[social]
email = "naiyu.yin@gmail.com"
location = "Bethlehem, PA, USA"
location_url = "https://maps.google.com/?q=Lehigh+University+Bethlehem+PA"
location_details = [
  "Department of Mathematics,",
  "Lehigh University, Bethlehem, PA, USA"
]
google_scholar = "https://scholar.google.com/citations?user=oWP6fNMAAAAJ"
github = "https://github.com/naiyuyin"
linkedin = "https://www.linkedin.com/in/naiyu-yin-21a15714a/"

[features]
enable_likes = true
enable_one_page_mode = false

[i18n]
enabled = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Experience"
type = "page"
target = "experience"
href = "/experience"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "link"
target = "cv"
href = "/CV_Naiyu_Yin.pdf"
